#!/bin/bash
set -e

case "$1" in

  configure)
    if ! id -u zcash &> /dev/null
    then
        useradd --system -M -U zcash -s /bin/false
    fi

    if [ "$(stat -c '%U' /opt/coins/data/zcash/backend)" != "zcash" ]
    then
        chown -R zcash:zcash /opt/coins/data/zcash/backend
    fi

    HOME=/opt/coins/data/zcash/backend /opt/coins/nodes/zcash/bin/zcash-fetch-params
  ;;

esac

#DEBHELPER#
