// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: bchain/coins/eth/ethtx.proto

package eth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoCompleteTransaction struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	BlockNumber   uint32                                `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	BlockTime     uint64                                `protobuf:"varint,2,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"`
	Tx            *ProtoCompleteTransaction_TxType      `protobuf:"bytes,3,opt,name=Tx,proto3" json:"Tx,omitempty"`
	Receipt       *ProtoCompleteTransaction_ReceiptType `protobuf:"bytes,4,opt,name=Receipt,proto3" json:"Receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoCompleteTransaction) Reset() {
	*x = ProtoCompleteTransaction{}
	mi := &file_bchain_coins_eth_ethtx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoCompleteTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoCompleteTransaction) ProtoMessage() {}

func (x *ProtoCompleteTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_bchain_coins_eth_ethtx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoCompleteTransaction.ProtoReflect.Descriptor instead.
func (*ProtoCompleteTransaction) Descriptor() ([]byte, []int) {
	return file_bchain_coins_eth_ethtx_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoCompleteTransaction) GetBlockNumber() uint32 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ProtoCompleteTransaction) GetBlockTime() uint64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *ProtoCompleteTransaction) GetTx() *ProtoCompleteTransaction_TxType {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *ProtoCompleteTransaction) GetReceipt() *ProtoCompleteTransaction_ReceiptType {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type ProtoCompleteTransaction_TxType struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccountNonce         uint64                 `protobuf:"varint,1,opt,name=AccountNonce,proto3" json:"AccountNonce,omitempty"`
	GasPrice             []byte                 `protobuf:"bytes,2,opt,name=GasPrice,proto3" json:"GasPrice,omitempty"`
	GasLimit             uint64                 `protobuf:"varint,3,opt,name=GasLimit,proto3" json:"GasLimit,omitempty"`
	Value                []byte                 `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Payload              []byte                 `protobuf:"bytes,5,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Hash                 []byte                 `protobuf:"bytes,6,opt,name=Hash,proto3" json:"Hash,omitempty"`
	To                   []byte                 `protobuf:"bytes,7,opt,name=To,proto3" json:"To,omitempty"`
	From                 []byte                 `protobuf:"bytes,8,opt,name=From,proto3" json:"From,omitempty"`
	TransactionIndex     uint32                 `protobuf:"varint,9,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
	MaxPriorityFeePerGas []byte                 `protobuf:"bytes,10,opt,name=MaxPriorityFeePerGas,proto3,oneof" json:"MaxPriorityFeePerGas,omitempty"`
	MaxFeePerGas         []byte                 `protobuf:"bytes,11,opt,name=MaxFeePerGas,proto3,oneof" json:"MaxFeePerGas,omitempty"`
	BaseFeePerGas        []byte                 `protobuf:"bytes,12,opt,name=BaseFeePerGas,proto3,oneof" json:"BaseFeePerGas,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProtoCompleteTransaction_TxType) Reset() {
	*x = ProtoCompleteTransaction_TxType{}
	mi := &file_bchain_coins_eth_ethtx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoCompleteTransaction_TxType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoCompleteTransaction_TxType) ProtoMessage() {}

func (x *ProtoCompleteTransaction_TxType) ProtoReflect() protoreflect.Message {
	mi := &file_bchain_coins_eth_ethtx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoCompleteTransaction_TxType.ProtoReflect.Descriptor instead.
func (*ProtoCompleteTransaction_TxType) Descriptor() ([]byte, []int) {
	return file_bchain_coins_eth_ethtx_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProtoCompleteTransaction_TxType) GetAccountNonce() uint64 {
	if x != nil {
		return x.AccountNonce
	}
	return 0
}

func (x *ProtoCompleteTransaction_TxType) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *ProtoCompleteTransaction_TxType) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ProtoCompleteTransaction_TxType) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProtoCompleteTransaction_TxType) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProtoCompleteTransaction_TxType) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ProtoCompleteTransaction_TxType) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ProtoCompleteTransaction_TxType) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ProtoCompleteTransaction_TxType) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *ProtoCompleteTransaction_TxType) GetMaxPriorityFeePerGas() []byte {
	if x != nil {
		return x.MaxPriorityFeePerGas
	}
	return nil
}

func (x *ProtoCompleteTransaction_TxType) GetMaxFeePerGas() []byte {
	if x != nil {
		return x.MaxFeePerGas
	}
	return nil
}

func (x *ProtoCompleteTransaction_TxType) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

type ProtoCompleteTransaction_ReceiptType struct {
	state             protoimpl.MessageState                          `protogen:"open.v1"`
	GasUsed           []byte                                          `protobuf:"bytes,1,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`
	Status            []byte                                          `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Log               []*ProtoCompleteTransaction_ReceiptType_LogType `protobuf:"bytes,3,rep,name=Log,proto3" json:"Log,omitempty"`
	L1Fee             []byte                                          `protobuf:"bytes,4,opt,name=L1Fee,proto3,oneof" json:"L1Fee,omitempty"`
	L1FeeScalar       []byte                                          `protobuf:"bytes,5,opt,name=L1FeeScalar,proto3,oneof" json:"L1FeeScalar,omitempty"`
	L1GasPrice        []byte                                          `protobuf:"bytes,6,opt,name=L1GasPrice,proto3,oneof" json:"L1GasPrice,omitempty"`
	L1GasUsed         []byte                                          `protobuf:"bytes,7,opt,name=L1GasUsed,proto3,oneof" json:"L1GasUsed,omitempty"`
	EffectiveGasPrice []byte                                          `protobuf:"bytes,8,opt,name=EffectiveGasPrice,proto3,oneof" json:"EffectiveGasPrice,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProtoCompleteTransaction_ReceiptType) Reset() {
	*x = ProtoCompleteTransaction_ReceiptType{}
	mi := &file_bchain_coins_eth_ethtx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoCompleteTransaction_ReceiptType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoCompleteTransaction_ReceiptType) ProtoMessage() {}

func (x *ProtoCompleteTransaction_ReceiptType) ProtoReflect() protoreflect.Message {
	mi := &file_bchain_coins_eth_ethtx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoCompleteTransaction_ReceiptType.ProtoReflect.Descriptor instead.
func (*ProtoCompleteTransaction_ReceiptType) Descriptor() ([]byte, []int) {
	return file_bchain_coins_eth_ethtx_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ProtoCompleteTransaction_ReceiptType) GetGasUsed() []byte {
	if x != nil {
		return x.GasUsed
	}
	return nil
}

func (x *ProtoCompleteTransaction_ReceiptType) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ProtoCompleteTransaction_ReceiptType) GetLog() []*ProtoCompleteTransaction_ReceiptType_LogType {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *ProtoCompleteTransaction_ReceiptType) GetL1Fee() []byte {
	if x != nil {
		return x.L1Fee
	}
	return nil
}

func (x *ProtoCompleteTransaction_ReceiptType) GetL1FeeScalar() []byte {
	if x != nil {
		return x.L1FeeScalar
	}
	return nil
}

func (x *ProtoCompleteTransaction_ReceiptType) GetL1GasPrice() []byte {
	if x != nil {
		return x.L1GasPrice
	}
	return nil
}

func (x *ProtoCompleteTransaction_ReceiptType) GetL1GasUsed() []byte {
	if x != nil {
		return x.L1GasUsed
	}
	return nil
}

func (x *ProtoCompleteTransaction_ReceiptType) GetEffectiveGasPrice() []byte {
	if x != nil {
		return x.EffectiveGasPrice
	}
	return nil
}

type ProtoCompleteTransaction_ReceiptType_LogType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Topics        [][]byte               `protobuf:"bytes,3,rep,name=Topics,proto3" json:"Topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoCompleteTransaction_ReceiptType_LogType) Reset() {
	*x = ProtoCompleteTransaction_ReceiptType_LogType{}
	mi := &file_bchain_coins_eth_ethtx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoCompleteTransaction_ReceiptType_LogType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoCompleteTransaction_ReceiptType_LogType) ProtoMessage() {}

func (x *ProtoCompleteTransaction_ReceiptType_LogType) ProtoReflect() protoreflect.Message {
	mi := &file_bchain_coins_eth_ethtx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoCompleteTransaction_ReceiptType_LogType.ProtoReflect.Descriptor instead.
func (*ProtoCompleteTransaction_ReceiptType_LogType) Descriptor() ([]byte, []int) {
	return file_bchain_coins_eth_ethtx_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ProtoCompleteTransaction_ReceiptType_LogType) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ProtoCompleteTransaction_ReceiptType_LogType) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProtoCompleteTransaction_ReceiptType_LogType) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_bchain_coins_eth_ethtx_proto protoreflect.FileDescriptor

const file_bchain_coins_eth_ethtx_proto_rawDesc = "" +
	"\n" +
	"\x1cbchain/coins/eth/ethtx.proto\"\xef\b\n" +
	"\x18ProtoCompleteTransaction\x12 \n" +
	"\vBlockNumber\x18\x01 \x01(\rR\vBlockNumber\x12\x1c\n" +
	"\tBlockTime\x18\x02 \x01(\x04R\tBlockTime\x120\n" +
	"\x02Tx\x18\x03 \x01(\v2 .ProtoCompleteTransaction.TxTypeR\x02Tx\x12?\n" +
	"\aReceipt\x18\x04 \x01(\v2%.ProtoCompleteTransaction.ReceiptTypeR\aReceipt\x1a\xc1\x03\n" +
	"\x06TxType\x12\"\n" +
	"\fAccountNonce\x18\x01 \x01(\x04R\fAccountNonce\x12\x1a\n" +
	"\bGasPrice\x18\x02 \x01(\fR\bGasPrice\x12\x1a\n" +
	"\bGasLimit\x18\x03 \x01(\x04R\bGasLimit\x12\x14\n" +
	"\x05Value\x18\x04 \x01(\fR\x05Value\x12\x18\n" +
	"\aPayload\x18\x05 \x01(\fR\aPayload\x12\x12\n" +
	"\x04Hash\x18\x06 \x01(\fR\x04Hash\x12\x0e\n" +
	"\x02To\x18\a \x01(\fR\x02To\x12\x12\n" +
	"\x04From\x18\b \x01(\fR\x04From\x12*\n" +
	"\x10TransactionIndex\x18\t \x01(\rR\x10TransactionIndex\x127\n" +
	"\x14MaxPriorityFeePerGas\x18\n" +
	" \x01(\fH\x00R\x14MaxPriorityFeePerGas\x88\x01\x01\x12'\n" +
	"\fMaxFeePerGas\x18\v \x01(\fH\x01R\fMaxFeePerGas\x88\x01\x01\x12)\n" +
	"\rBaseFeePerGas\x18\f \x01(\fH\x02R\rBaseFeePerGas\x88\x01\x01B\x17\n" +
	"\x15_MaxPriorityFeePerGasB\x0f\n" +
	"\r_MaxFeePerGasB\x10\n" +
	"\x0e_BaseFeePerGas\x1a\xdb\x03\n" +
	"\vReceiptType\x12\x18\n" +
	"\aGasUsed\x18\x01 \x01(\fR\aGasUsed\x12\x16\n" +
	"\x06Status\x18\x02 \x01(\fR\x06Status\x12?\n" +
	"\x03Log\x18\x03 \x03(\v2-.ProtoCompleteTransaction.ReceiptType.LogTypeR\x03Log\x12\x19\n" +
	"\x05L1Fee\x18\x04 \x01(\fH\x00R\x05L1Fee\x88\x01\x01\x12%\n" +
	"\vL1FeeScalar\x18\x05 \x01(\fH\x01R\vL1FeeScalar\x88\x01\x01\x12#\n" +
	"\n" +
	"L1GasPrice\x18\x06 \x01(\fH\x02R\n" +
	"L1GasPrice\x88\x01\x01\x12!\n" +
	"\tL1GasUsed\x18\a \x01(\fH\x03R\tL1GasUsed\x88\x01\x01\x121\n" +
	"\x11EffectiveGasPrice\x18\b \x01(\fH\x04R\x11EffectiveGasPrice\x88\x01\x01\x1aO\n" +
	"\aLogType\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\fR\aAddress\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\x12\x16\n" +
	"\x06Topics\x18\x03 \x03(\fR\x06TopicsB\b\n" +
	"\x06_L1FeeB\x0e\n" +
	"\f_L1FeeScalarB\r\n" +
	"\v_L1GasPriceB\f\n" +
	"\n" +
	"_L1GasUsedB\x14\n" +
	"\x12_EffectiveGasPriceB\x12Z\x10bchain/coins/ethb\x06proto3"

var (
	file_bchain_coins_eth_ethtx_proto_rawDescOnce sync.Once
	file_bchain_coins_eth_ethtx_proto_rawDescData []byte
)

func file_bchain_coins_eth_ethtx_proto_rawDescGZIP() []byte {
	file_bchain_coins_eth_ethtx_proto_rawDescOnce.Do(func() {
		file_bchain_coins_eth_ethtx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bchain_coins_eth_ethtx_proto_rawDesc), len(file_bchain_coins_eth_ethtx_proto_rawDesc)))
	})
	return file_bchain_coins_eth_ethtx_proto_rawDescData
}

var file_bchain_coins_eth_ethtx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bchain_coins_eth_ethtx_proto_goTypes = []any{
	(*ProtoCompleteTransaction)(nil),                     // 0: ProtoCompleteTransaction
	(*ProtoCompleteTransaction_TxType)(nil),              // 1: ProtoCompleteTransaction.TxType
	(*ProtoCompleteTransaction_ReceiptType)(nil),         // 2: ProtoCompleteTransaction.ReceiptType
	(*ProtoCompleteTransaction_ReceiptType_LogType)(nil), // 3: ProtoCompleteTransaction.ReceiptType.LogType
}
var file_bchain_coins_eth_ethtx_proto_depIdxs = []int32{
	1, // 0: ProtoCompleteTransaction.Tx:type_name -> ProtoCompleteTransaction.TxType
	2, // 1: ProtoCompleteTransaction.Receipt:type_name -> ProtoCompleteTransaction.ReceiptType
	3, // 2: ProtoCompleteTransaction.ReceiptType.Log:type_name -> ProtoCompleteTransaction.ReceiptType.LogType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bchain_coins_eth_ethtx_proto_init() }
func file_bchain_coins_eth_ethtx_proto_init() {
	if File_bchain_coins_eth_ethtx_proto != nil {
		return
	}
	file_bchain_coins_eth_ethtx_proto_msgTypes[1].OneofWrappers = []any{}
	file_bchain_coins_eth_ethtx_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bchain_coins_eth_ethtx_proto_rawDesc), len(file_bchain_coins_eth_ethtx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bchain_coins_eth_ethtx_proto_goTypes,
		DependencyIndexes: file_bchain_coins_eth_ethtx_proto_depIdxs,
		MessageInfos:      file_bchain_coins_eth_ethtx_proto_msgTypes,
	}.Build()
	File_bchain_coins_eth_ethtx_proto = out.File
	file_bchain_coins_eth_ethtx_proto_goTypes = nil
	file_bchain_coins_eth_ethtx_proto_depIdxs = nil
}
