// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: xcbtx.proto

package xcb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoXCBCompleteTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNumber uint32                                   `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	BlockTime   uint64                                   `protobuf:"varint,2,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"`
	Tx          *ProtoXCBCompleteTransaction_TxType      `protobuf:"bytes,3,opt,name=Tx,proto3" json:"Tx,omitempty"`
	Receipt     *ProtoXCBCompleteTransaction_ReceiptType `protobuf:"bytes,4,opt,name=Receipt,proto3" json:"Receipt,omitempty"`
}

func (x *ProtoXCBCompleteTransaction) Reset() {
	*x = ProtoXCBCompleteTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xcbtx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoXCBCompleteTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoXCBCompleteTransaction) ProtoMessage() {}

func (x *ProtoXCBCompleteTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_xcbtx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoXCBCompleteTransaction.ProtoReflect.Descriptor instead.
func (*ProtoXCBCompleteTransaction) Descriptor() ([]byte, []int) {
	return file_xcbtx_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoXCBCompleteTransaction) GetBlockNumber() uint32 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ProtoXCBCompleteTransaction) GetBlockTime() uint64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *ProtoXCBCompleteTransaction) GetTx() *ProtoXCBCompleteTransaction_TxType {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction) GetReceipt() *ProtoXCBCompleteTransaction_ReceiptType {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type ProtoXCBCompleteTransaction_TxType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountNonce     uint64 `protobuf:"varint,1,opt,name=AccountNonce,proto3" json:"AccountNonce,omitempty"`
	EnergyPrice      []byte `protobuf:"bytes,2,opt,name=EnergyPrice,proto3" json:"EnergyPrice,omitempty"`
	EnergyLimit      uint64 `protobuf:"varint,3,opt,name=EnergyLimit,proto3" json:"EnergyLimit,omitempty"`
	Value            []byte `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Payload          []byte `protobuf:"bytes,5,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Hash             []byte `protobuf:"bytes,6,opt,name=Hash,proto3" json:"Hash,omitempty"`
	To               []byte `protobuf:"bytes,7,opt,name=To,proto3" json:"To,omitempty"`
	From             []byte `protobuf:"bytes,8,opt,name=From,proto3" json:"From,omitempty"`
	TransactionIndex uint32 `protobuf:"varint,9,opt,name=TransactionIndex,proto3" json:"TransactionIndex,omitempty"`
}

func (x *ProtoXCBCompleteTransaction_TxType) Reset() {
	*x = ProtoXCBCompleteTransaction_TxType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xcbtx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoXCBCompleteTransaction_TxType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoXCBCompleteTransaction_TxType) ProtoMessage() {}

func (x *ProtoXCBCompleteTransaction_TxType) ProtoReflect() protoreflect.Message {
	mi := &file_xcbtx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoXCBCompleteTransaction_TxType.ProtoReflect.Descriptor instead.
func (*ProtoXCBCompleteTransaction_TxType) Descriptor() ([]byte, []int) {
	return file_xcbtx_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ProtoXCBCompleteTransaction_TxType) GetAccountNonce() uint64 {
	if x != nil {
		return x.AccountNonce
	}
	return 0
}

func (x *ProtoXCBCompleteTransaction_TxType) GetEnergyPrice() []byte {
	if x != nil {
		return x.EnergyPrice
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_TxType) GetEnergyLimit() uint64 {
	if x != nil {
		return x.EnergyLimit
	}
	return 0
}

func (x *ProtoXCBCompleteTransaction_TxType) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_TxType) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_TxType) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_TxType) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_TxType) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_TxType) GetTransactionIndex() uint32 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

type ProtoXCBCompleteTransaction_ReceiptType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnergyUsed []byte                                             `protobuf:"bytes,1,opt,name=EnergyUsed,proto3" json:"EnergyUsed,omitempty"`
	Status     []byte                                             `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	Log        []*ProtoXCBCompleteTransaction_ReceiptType_LogType `protobuf:"bytes,3,rep,name=Log,proto3" json:"Log,omitempty"`
}

func (x *ProtoXCBCompleteTransaction_ReceiptType) Reset() {
	*x = ProtoXCBCompleteTransaction_ReceiptType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xcbtx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoXCBCompleteTransaction_ReceiptType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoXCBCompleteTransaction_ReceiptType) ProtoMessage() {}

func (x *ProtoXCBCompleteTransaction_ReceiptType) ProtoReflect() protoreflect.Message {
	mi := &file_xcbtx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoXCBCompleteTransaction_ReceiptType.ProtoReflect.Descriptor instead.
func (*ProtoXCBCompleteTransaction_ReceiptType) Descriptor() ([]byte, []int) {
	return file_xcbtx_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ProtoXCBCompleteTransaction_ReceiptType) GetEnergyUsed() []byte {
	if x != nil {
		return x.EnergyUsed
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_ReceiptType) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_ReceiptType) GetLog() []*ProtoXCBCompleteTransaction_ReceiptType_LogType {
	if x != nil {
		return x.Log
	}
	return nil
}

type ProtoXCBCompleteTransaction_ReceiptType_LogType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Data    []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Topics  [][]byte `protobuf:"bytes,3,rep,name=Topics,proto3" json:"Topics,omitempty"`
}

func (x *ProtoXCBCompleteTransaction_ReceiptType_LogType) Reset() {
	*x = ProtoXCBCompleteTransaction_ReceiptType_LogType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xcbtx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoXCBCompleteTransaction_ReceiptType_LogType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoXCBCompleteTransaction_ReceiptType_LogType) ProtoMessage() {}

func (x *ProtoXCBCompleteTransaction_ReceiptType_LogType) ProtoReflect() protoreflect.Message {
	mi := &file_xcbtx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoXCBCompleteTransaction_ReceiptType_LogType.ProtoReflect.Descriptor instead.
func (*ProtoXCBCompleteTransaction_ReceiptType_LogType) Descriptor() ([]byte, []int) {
	return file_xcbtx_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ProtoXCBCompleteTransaction_ReceiptType_LogType) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_ReceiptType_LogType) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProtoXCBCompleteTransaction_ReceiptType_LogType) GetTopics() [][]byte {
	if x != nil {
		return x.Topics
	}
	return nil
}

var File_xcbtx_proto protoreflect.FileDescriptor

var file_xcbtx_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x78, 0x63, 0x62, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x78,
	0x63, 0x62, 0x22, 0xc6, 0x05, 0x0a, 0x1b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x58, 0x43, 0x42, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x37, 0x0a, 0x02, 0x54, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x78, 0x63, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x58, 0x43, 0x42, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x54, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x54, 0x78, 0x12, 0x46, 0x0a, 0x07, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x78,
	0x63, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x58, 0x43, 0x42, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x70, 0x74, 0x1a, 0x84, 0x02, 0x0a, 0x06, 0x54, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x45, 0x6e, 0x65, 0x72, 0x67,
	0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72,
	0x6f, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x2a,
	0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0xde, 0x01, 0x0a, 0x0b, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x55, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x55, 0x73, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x46, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x34, 0x2e, 0x78, 0x63, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x58, 0x43, 0x42, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x4c, 0x6f,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x4c, 0x6f, 0x67, 0x1a, 0x4f, 0x0a, 0x07, 0x4c, 0x6f,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_xcbtx_proto_rawDescOnce sync.Once
	file_xcbtx_proto_rawDescData = file_xcbtx_proto_rawDesc
)

func file_xcbtx_proto_rawDescGZIP() []byte {
	file_xcbtx_proto_rawDescOnce.Do(func() {
		file_xcbtx_proto_rawDescData = protoimpl.X.CompressGZIP(file_xcbtx_proto_rawDescData)
	})
	return file_xcbtx_proto_rawDescData
}

var file_xcbtx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xcbtx_proto_goTypes = []interface{}{
	(*ProtoXCBCompleteTransaction)(nil),                     // 0: xcb.ProtoXCBCompleteTransaction
	(*ProtoXCBCompleteTransaction_TxType)(nil),              // 1: xcb.ProtoXCBCompleteTransaction.TxType
	(*ProtoXCBCompleteTransaction_ReceiptType)(nil),         // 2: xcb.ProtoXCBCompleteTransaction.ReceiptType
	(*ProtoXCBCompleteTransaction_ReceiptType_LogType)(nil), // 3: xcb.ProtoXCBCompleteTransaction.ReceiptType.LogType
}
var file_xcbtx_proto_depIdxs = []int32{
	1, // 0: xcb.ProtoXCBCompleteTransaction.Tx:type_name -> xcb.ProtoXCBCompleteTransaction.TxType
	2, // 1: xcb.ProtoXCBCompleteTransaction.Receipt:type_name -> xcb.ProtoXCBCompleteTransaction.ReceiptType
	3, // 2: xcb.ProtoXCBCompleteTransaction.ReceiptType.Log:type_name -> xcb.ProtoXCBCompleteTransaction.ReceiptType.LogType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_xcbtx_proto_init() }
func file_xcbtx_proto_init() {
	if File_xcbtx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xcbtx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoXCBCompleteTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xcbtx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoXCBCompleteTransaction_TxType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xcbtx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoXCBCompleteTransaction_ReceiptType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xcbtx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoXCBCompleteTransaction_ReceiptType_LogType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xcbtx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xcbtx_proto_goTypes,
		DependencyIndexes: file_xcbtx_proto_depIdxs,
		MessageInfos:      file_xcbtx_proto_msgTypes,
	}.Build()
	File_xcbtx_proto = out.File
	file_xcbtx_proto_rawDesc = nil
	file_xcbtx_proto_goTypes = nil
	file_xcbtx_proto_depIdxs = nil
}
