//go:build unittest

package fiat

import (
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/trezor/blockbook/common"
)

const cloudfrontBlockedBody = "<HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY><H1>403 ERROR</H1>Request blocked.<PRE>Generated by cloudfront (CloudFront)</PRE></BODY></HTML>"

func TestBatchIdsByParamLen(t *testing.T) {
	long := strings.Repeat("x", 30)
	tests := []struct {
		name   string
		ids    []string
		maxLen int
		want   [][]string
	}{
		{name: "empty", ids: nil, maxLen: 10, want: nil},
		{name: "single batch", ids: []string{"a", "b", "c"}, maxLen: 100, want: [][]string{{"a", "b", "c"}}},
		// "aaa%2Cbbb" is 9 chars, adding "%2Cccc" would make 15
		{name: "separator counted", ids: []string{"aaa", "bbb", "ccc"}, maxLen: 14, want: [][]string{{"aaa", "bbb"}, {"ccc"}}},
		{name: "exact fit", ids: []string{"aaa", "bbb", "ccc"}, maxLen: 15, want: [][]string{{"aaa", "bbb", "ccc"}}},
		{name: "oversized id alone", ids: []string{"a", long, "b"}, maxLen: 10, want: [][]string{{"a"}, {long}, {"b"}}},
		{name: "escaped length", ids: []string{"a b", "c"}, maxLen: 5, want: [][]string{{"a b"}, {"c"}}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := batchIdsByParamLen(tt.ids, tt.maxLen); !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("batchIdsByParamLen() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestBatchIdsByParamLen_BatchesStayWithinLimit(t *testing.T) {
	ids := make([]string, 0, 5000)
	for i := 0; i < cap(ids); i++ {
		ids = append(ids, fmt.Sprintf("token-%d-%s", i, strings.Repeat("y", i%40)))
	}
	batches := batchIdsByParamLen(ids, coingeckoMaxIdsParamLen)
	var joined []string
	for _, b := range batches {
		if l := len(url.QueryEscape(strings.Join(b, ","))); l > coingeckoMaxIdsParamLen {
			t.Fatalf("batch ids param is %d chars, limit %d", l, coingeckoMaxIdsParamLen)
		}
		joined = append(joined, b...)
	}
	if !reflect.DeepEqual(joined, ids) {
		t.Fatal("batches do not preserve all ids in order")
	}
}

// newCurrentTickersTestCoingecko serves a token platform of n ids where the batch containing
// blockedID is rejected the way the CloudFront WAF rejects a request, and every URL longer than
// the observed WAF limit is rejected too.
func newCurrentTickersTestCoingecko(t *testing.T, n int, blockedID string, coinsListStatus int) (*Coingecko, map[string]float32) {
	t.Helper()
	var coins []string
	wantTokenRates := make(map[string]float32)
	for i := 0; i < n; i++ {
		id := fmt.Sprintf("token-%04d", i)
		contract := fmt.Sprintf("0x%040x", i)
		coins = append(coins, fmt.Sprintf(`{"id":%q,"symbol":"t","name":"t","platforms":{"ethereum":%q}}`, id, contract))
		wantTokenRates[contract] = float32(i + 1)
	}
	coinsList := "[" + strings.Join(coins, ",") + "]"
	transport := roundTripFunc(func(r *http.Request) (*http.Response, error) {
		if len(r.URL.String()) > 3000 {
			return stubHTTPResponse(http.StatusForbidden, cloudfrontBlockedBody), nil
		}
		switch r.URL.Path {
		case "/simple/supported_vs_currencies":
			return stubHTTPResponse(http.StatusOK, `["usd","eur"]`), nil
		case "/coins/list":
			if coinsListStatus != http.StatusOK {
				return stubHTTPResponse(coinsListStatus, cloudfrontBlockedBody), nil
			}
			return stubHTTPResponse(http.StatusOK, coinsList), nil
		case "/simple/price":
			ids := strings.Split(r.URL.Query().Get("ids"), ",")
			if ids[0] == "ethereum" {
				return stubHTTPResponse(http.StatusOK, `{"ethereum":{"usd":2000,"eur":1800}}`), nil
			}
			parts := make([]string, 0, len(ids))
			for _, id := range ids {
				if id == blockedID {
					return stubHTTPResponse(http.StatusForbidden, cloudfrontBlockedBody), nil
				}
				var i int
				fmt.Sscanf(id, "token-%04d", &i)
				parts = append(parts, fmt.Sprintf(`%q:{"eth":%d}`, id, i+1))
			}
			return stubHTTPResponse(http.StatusOK, "{"+strings.Join(parts, ",")+"}"), nil
		}
		return stubHTTPResponse(http.StatusNotFound, "unexpected path "+r.URL.Path), nil
	})
	return &Coingecko{
		coin:               "ethereum",
		platformIdentifier: "ethereum",
		platformVsCurrency: "eth",
		tipURL:             "http://coingecko.test",
		httpClient:         &http.Client{Transport: transport},
		plan:               coingeckoPlanFree,
	}, wantTokenRates
}

func TestCurrentTickers_AllTokenBatchesFitUnderWAFLimit(t *testing.T) {
	// 1000 ids of 10 chars need several batches; a single oversized one would be rejected
	cg, wantTokenRates := newCurrentTickersTestCoingecko(t, 1000, "", http.StatusOK)
	ticker, err := cg.CurrentTickers()
	if err != nil {
		t.Fatalf("CurrentTickers() error = %v", err)
	}
	if !reflect.DeepEqual(ticker.TokenRates, wantTokenRates) {
		t.Fatalf("got %d token rates, want %d", len(ticker.TokenRates), len(wantTokenRates))
	}
}

func TestCurrentTickers_FailedTokenBatchKeepsNativeAndOtherTokenRates(t *testing.T) {
	cg, allTokenRates := newCurrentTickersTestCoingecko(t, 1000, "token-0000", http.StatusOK)
	ticker, err := cg.CurrentTickers()
	if !errors.Is(err, errCoingeckoIncompleteTokenRates) {
		t.Fatalf("CurrentTickers() error = %v, want errCoingeckoIncompleteTokenRates", err)
	}
	if ticker == nil {
		t.Fatal("expected a ticker with the rates that were fetched")
	}
	if want := map[string]float32{"usd": 2000, "eur": 1800}; !reflect.DeepEqual(ticker.Rates, want) {
		t.Fatalf("Rates = %v, want %v", ticker.Rates, want)
	}
	if ticker.Timestamp.IsZero() {
		t.Fatal("expected ticker timestamp to be set")
	}
	if _, found := ticker.TokenRates[fmt.Sprintf("0x%040x", 0)]; found {
		t.Fatal("token from the failed batch must be missing")
	}
	if len(ticker.TokenRates) == 0 || len(ticker.TokenRates) >= len(allTokenRates) {
		t.Fatalf("got %d token rates, want only those of the successful batches (< %d)", len(ticker.TokenRates), len(allTokenRates))
	}
	for contract, rate := range ticker.TokenRates {
		if allTokenRates[contract] != rate {
			t.Fatalf("TokenRates[%s] = %v, want %v", contract, rate, allTokenRates[contract])
		}
	}
}

func TestCurrentTickers_FailedCoinsListKeepsNativeRates(t *testing.T) {
	cg, _ := newCurrentTickersTestCoingecko(t, 10, "", http.StatusForbidden)
	ticker, err := cg.CurrentTickers()
	if !errors.Is(err, errCoingeckoIncompleteTokenRates) {
		t.Fatalf("CurrentTickers() error = %v, want errCoingeckoIncompleteTokenRates", err)
	}
	if ticker == nil || ticker.Rates["usd"] != 2000 {
		t.Fatalf("expected native rates to survive a failed coins/list, got %+v", ticker)
	}
}

type stubCurrentTickersDownloader struct {
	RatesDownloaderInterface
	ticker *common.CurrencyRatesTicker
	err    error
}

func (s *stubCurrentTickersDownloader) CurrentTickers() (*common.CurrencyRatesTicker, error) {
	return s.ticker, s.err
}

func TestUpdateCurrentTickers(t *testing.T) {
	prevTs := time.Now().Add(-time.Hour).UTC()
	newTs := time.Now().UTC()
	prev := func() *common.CurrencyRatesTicker {
		return &common.CurrencyRatesTicker{
			Timestamp:  prevTs,
			Rates:      map[string]float32{"usd": 1},
			TokenRates: map[string]float32{"0xa": 10, "0xb": 20},
		}
	}
	tests := []struct {
		name     string
		prev     *common.CurrencyRatesTicker
		ticker   *common.CurrencyRatesTicker
		err      error
		want     *common.CurrencyRatesTicker
		notified bool
	}{
		{
			name:     "complete ticker replaces previous one",
			prev:     prev(),
			ticker:   &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}, TokenRates: map[string]float32{"0xa": 11}},
			want:     &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}, TokenRates: map[string]float32{"0xa": 11}},
			notified: true,
		},
		{
			name:     "incomplete tokens keep previous rates of missing tokens",
			prev:     prev(),
			ticker:   &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}, TokenRates: map[string]float32{"0xa": 11}},
			err:      fmt.Errorf("%w: 1 of 2 batches failed", errCoingeckoIncompleteTokenRates),
			want:     &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}, TokenRates: map[string]float32{"0xa": 11, "0xb": 20}},
			notified: true,
		},
		{
			name:     "incomplete tokens without previous ticker",
			ticker:   &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}},
			err:      fmt.Errorf("%w: coins/list failed", errCoingeckoIncompleteTokenRates),
			want:     &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}},
			notified: true,
		},
		{
			name: "native failure keeps previous ticker",
			prev: prev(),
			err:  errors.New("simple/price failed"),
			want: prev(),
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			config := common.Config{CoinName: "fakecoin"}
			d, _, tmp := setupRocksDB(t, &testBitcoinParser{BitcoinParser: bitcoinTestnetParser()}, &config)
			defer closeAndDestroyRocksDB(t, d, tmp)
			notified := false
			fr := &FiatRates{
				db:                  d,
				currentTicker:       tt.prev,
				downloader:          &stubCurrentTickersDownloader{ticker: tt.ticker, err: tt.err},
				callbackOnNewTicker: func(*common.CurrencyRatesTicker) { notified = true },
			}
			fr.updateCurrentTickers()
			if got := fr.GetCurrentTicker("", ""); !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("current ticker = %+v, want %+v", got, tt.want)
			}
			if notified != tt.notified {
				t.Fatalf("notified = %v, want %v", notified, tt.notified)
			}
			if !tt.notified {
				return
			}
			stored, err := d.FiatRatesGetSpecialTickers(currentTickersKey)
			if err != nil || stored == nil || len(*stored) != 1 {
				t.Fatalf("stored current ticker = %v, %v", stored, err)
			}
			if got := (*stored)[0].TokenRates; len(got)+len(tt.want.TokenRates) > 0 && !reflect.DeepEqual(got, tt.want.TokenRates) {
				t.Fatalf("stored TokenRates = %v, want %v", (*stored)[0].TokenRates, tt.want.TokenRates)
			}
		})
	}
}
