//go:build unittest

package fiat

import (
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/trezor/blockbook/common"
)

const cloudfrontBlockedBody = "<HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY><H1>403 ERROR</H1>Request blocked.<PRE>Generated by cloudfront (CloudFront)</PRE></BODY></HTML>"

func TestBatchIdsByParamLen(t *testing.T) {
	long := strings.Repeat("x", 30)
	tests := []struct {
		name   string
		ids    []string
		maxLen int
		want   [][]string
	}{
		{name: "empty", ids: nil, maxLen: 10, want: nil},
		{name: "single batch", ids: []string{"a", "b", "c"}, maxLen: 100, want: [][]string{{"a", "b", "c"}}},
		// "aaa%2Cbbb" is 9 chars, adding "%2Cccc" would make 15
		{name: "separator counted", ids: []string{"aaa", "bbb", "ccc"}, maxLen: 14, want: [][]string{{"aaa", "bbb"}, {"ccc"}}},
		{name: "exact fit", ids: []string{"aaa", "bbb", "ccc"}, maxLen: 15, want: [][]string{{"aaa", "bbb", "ccc"}}},
		{name: "oversized id alone", ids: []string{"a", long, "b"}, maxLen: 10, want: [][]string{{"a"}, {long}, {"b"}}},
		{name: "escaped length", ids: []string{"a b", "c"}, maxLen: 5, want: [][]string{{"a b"}, {"c"}}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := batchIdsByParamLen(tt.ids, tt.maxLen); !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("batchIdsByParamLen() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestBatchIdsByParamLen_BatchesStayWithinLimit(t *testing.T) {
	ids := make([]string, 0, 5000)
	for i := 0; i < cap(ids); i++ {
		ids = append(ids, fmt.Sprintf("token-%d-%s", i, strings.Repeat("y", i%40)))
	}
	const maxLen = 1900
	batches := batchIdsByParamLen(ids, maxLen)
	var joined []string
	for _, b := range batches {
		if l := len(url.QueryEscape(strings.Join(b, ","))); l > maxLen {
			t.Fatalf("batch ids param is %d chars, limit %d", l, maxLen)
		}
		joined = append(joined, b...)
	}
	if !reflect.DeepEqual(joined, ids) {
		t.Fatal("batches do not preserve all ids in order")
	}
}

// stubCoingecko serves a token platform of n ids like the api.coingecko.com CloudFront edge: a
// query string over coingeckoMaxQueryLen is rejected with 403. The batch containing blockedID is
// rejected with blockedBody (CloudFront 403 by default) the first blockedTimes times (-1: always).
type stubCoingecko struct {
	n               int
	blockedID       string
	blockedTimes    int
	blockedBody     string
	coinsListStatus int

	tokenRequests int
	maxQueryLen   int
	firstTokenAt  time.Time
}

func (s *stubCoingecko) roundTrip(r *http.Request) (*http.Response, error) {
	if len(r.URL.RawQuery) > coingeckoMaxQueryLen {
		return stubHTTPResponse(http.StatusForbidden, cloudfrontBlockedBody), nil
	}
	switch r.URL.Path {
	case "/simple/supported_vs_currencies":
		return stubHTTPResponse(http.StatusOK, `["usd","eur"]`), nil
	case "/coins/list":
		if s.coinsListStatus != 0 && s.coinsListStatus != http.StatusOK {
			return stubHTTPResponse(s.coinsListStatus, cloudfrontBlockedBody), nil
		}
		coins := make([]string, 0, s.n)
		for i := 0; i < s.n; i++ {
			coins = append(coins, fmt.Sprintf(`{"id":"token-%04d","symbol":"t","name":"t","platforms":{"ethereum":"0x%040x"}}`, i, i))
		}
		return stubHTTPResponse(http.StatusOK, "["+strings.Join(coins, ",")+"]"), nil
	case "/simple/price":
		ids := strings.Split(r.URL.Query().Get("ids"), ",")
		if ids[0] == "ethereum" {
			return stubHTTPResponse(http.StatusOK, `{"ethereum":{"usd":2000,"eur":1800}}`), nil
		}
		if s.tokenRequests == 0 {
			s.firstTokenAt = time.Now().UTC()
		}
		s.tokenRequests++
		if len(r.URL.RawQuery) > s.maxQueryLen {
			s.maxQueryLen = len(r.URL.RawQuery)
		}
		parts := make([]string, 0, len(ids))
		for _, id := range ids {
			if id == s.blockedID && s.blockedTimes != 0 {
				s.blockedTimes--
				body := s.blockedBody
				if body == "" {
					body = cloudfrontBlockedBody
				}
				return stubHTTPResponse(http.StatusForbidden, body), nil
			}
			var i int
			fmt.Sscanf(id, "token-%04d", &i)
			parts = append(parts, fmt.Sprintf(`%q:{"eth":%d}`, id, i+1))
		}
		return stubHTTPResponse(http.StatusOK, "{"+strings.Join(parts, ",")+"}"), nil
	}
	return stubHTTPResponse(http.StatusNotFound, "unexpected path "+r.URL.Path), nil
}

func (s *stubCoingecko) coingecko() *Coingecko {
	return &Coingecko{
		coin:               "ethereum",
		platformIdentifier: "ethereum",
		platformVsCurrency: "eth",
		tipURL:             "http://coingecko.test",
		httpClient:         &http.Client{Transport: roundTripFunc(s.roundTrip)},
		plan:               coingeckoPlanFree,
	}
}

func stubTokenRates(n int) map[string]float32 {
	rates := make(map[string]float32, n)
	for i := 0; i < n; i++ {
		rates[fmt.Sprintf("0x%040x", i)] = float32(i + 1)
	}
	return rates
}

func tokenBatchCount(n int) int {
	ids := make([]string, n)
	for i := range ids {
		ids[i] = fmt.Sprintf("token-%04d", i)
	}
	return len(batchIdsByParamLen(ids, tokenPriceIdsBudget("eth")))
}

func TestCurrentTickers_TokenBatchesFitUnderQueryLimit(t *testing.T) {
	// 1000 ids of 10 chars need several batches; a single oversized one would be rejected
	stub := &stubCoingecko{n: 1000}
	ticker, err := stub.coingecko().CurrentTickers()
	if err != nil {
		t.Fatalf("CurrentTickers() error = %v", err)
	}
	if limit := coingeckoMaxQueryLen - coingeckoQueryLenMargin; stub.maxQueryLen > limit || stub.maxQueryLen < limit-20 {
		t.Fatalf("longest token-price query is %d chars, want just under %d", stub.maxQueryLen, limit)
	}
	if !reflect.DeepEqual(ticker.TokenRates, stubTokenRates(1000)) {
		t.Fatalf("got %d token rates, want %d", len(ticker.TokenRates), 1000)
	}
	if want := tokenBatchCount(1000); stub.tokenRequests != want || want < 2 {
		t.Fatalf("token requests = %d, want %d (>= 2)", stub.tokenRequests, want)
	}
}

func TestCurrentTickers_TimestampIsNativeFetchTime(t *testing.T) {
	stub := &stubCoingecko{n: 1000}
	before := time.Now().UTC()
	ticker, err := stub.coingecko().CurrentTickers()
	if err != nil {
		t.Fatalf("CurrentTickers() error = %v", err)
	}
	if ticker.Timestamp.Before(before) || ticker.Timestamp.After(stub.firstTokenAt) {
		t.Fatalf("Timestamp = %v, want between start %v and the first token request %v", ticker.Timestamp, before, stub.firstTokenAt)
	}
}

func TestCurrentTickers_TransientBatchFailureIsRetried(t *testing.T) {
	stub := &stubCoingecko{n: 1000, blockedID: "token-0000", blockedTimes: 1}
	ticker, err := stub.coingecko().CurrentTickers()
	if err != nil {
		t.Fatalf("CurrentTickers() error = %v", err)
	}
	if !reflect.DeepEqual(ticker.TokenRates, stubTokenRates(1000)) {
		t.Fatalf("got %d token rates, want all %d after the retry", len(ticker.TokenRates), 1000)
	}
	if want := tokenBatchCount(1000) + 1; stub.tokenRequests != want {
		t.Fatalf("token requests = %d, want %d (one retry)", stub.tokenRequests, want)
	}
}

func TestCurrentTickers_FailedTokenBatchKeepsNativeAndOtherTokenRates(t *testing.T) {
	stub := &stubCoingecko{n: 1000, blockedID: "token-0000", blockedTimes: -1}
	ticker, err := stub.coingecko().CurrentTickers()
	if !errors.Is(err, errCoingeckoIncompleteTokenRates) {
		t.Fatalf("CurrentTickers() error = %v, want errCoingeckoIncompleteTokenRates", err)
	}
	if ticker == nil {
		t.Fatal("expected a ticker with the rates that were fetched")
	}
	if want := map[string]float32{"usd": 2000, "eur": 1800}; !reflect.DeepEqual(ticker.Rates, want) {
		t.Fatalf("Rates = %v, want %v", ticker.Rates, want)
	}
	if ticker.Timestamp.IsZero() {
		t.Fatal("expected ticker timestamp to be set")
	}
	if _, found := ticker.TokenRates[fmt.Sprintf("0x%040x", 0)]; found {
		t.Fatal("token from the failed batch must be missing")
	}
	all := stubTokenRates(1000)
	if len(ticker.TokenRates) == 0 || len(ticker.TokenRates) >= len(all) {
		t.Fatalf("got %d token rates, want only those of the successful batches (< %d)", len(ticker.TokenRates), len(all))
	}
	for contract, rate := range ticker.TokenRates {
		if all[contract] != rate {
			t.Fatalf("TokenRates[%s] = %v, want %v", contract, rate, all[contract])
		}
	}
	if want := tokenBatchCount(1000) + 1; stub.tokenRequests != want {
		t.Fatalf("token requests = %d, want %d (failed batch retried exactly once)", stub.tokenRequests, want)
	}
}

func TestCurrentTickers_CloudflareBanStopsWithoutRetry(t *testing.T) {
	// the ban hits the second batch: the first one is kept, the rest is neither requested nor retried
	ids := make([]string, 1000)
	for i := range ids {
		ids[i] = fmt.Sprintf("token-%04d", i)
	}
	batches := batchIdsByParamLen(ids, tokenPriceIdsBudget("eth"))
	stub := &stubCoingecko{n: 1000, blockedID: batches[1][0], blockedTimes: -1, blockedBody: cloudflareBanBody}
	ticker, err := stub.coingecko().CurrentTickers()
	if !errors.Is(err, errCoingeckoIncompleteTokenRates) {
		t.Fatalf("CurrentTickers() error = %v, want errCoingeckoIncompleteTokenRates", err)
	}
	if want := fmt.Sprintf("%d of %d batches failed", len(batches)-1, len(batches)); !strings.Contains(err.Error(), want) {
		t.Fatalf("error = %v, want it to report %q", err, want)
	}
	if stub.tokenRequests != 2 {
		t.Fatalf("token requests = %d, want 2 (stop at the ban, no retry)", stub.tokenRequests)
	}
	if len(ticker.TokenRates) != len(batches[0]) || ticker.Rates["usd"] != 2000 {
		t.Fatalf("got %d token rates and usd %v, want %d tokens of the first batch and native rates", len(ticker.TokenRates), ticker.Rates["usd"], len(batches[0]))
	}
}

func TestCurrentTickers_FailedCoinsListKeepsNativeRates(t *testing.T) {
	stub := &stubCoingecko{n: 10, coinsListStatus: http.StatusForbidden}
	ticker, err := stub.coingecko().CurrentTickers()
	if !errors.Is(err, errCoingeckoIncompleteTokenRates) {
		t.Fatalf("CurrentTickers() error = %v, want errCoingeckoIncompleteTokenRates", err)
	}
	if ticker == nil || ticker.Rates["usd"] != 2000 || ticker.Timestamp.IsZero() || len(ticker.TokenRates) != 0 {
		t.Fatalf("expected native rates and timestamp without token rates, got %+v", ticker)
	}
}

type stubCurrentTickersDownloader struct {
	RatesDownloaderInterface
	ticker *common.CurrencyRatesTicker
	err    error
}

func (s *stubCurrentTickersDownloader) CurrentTickers() (*common.CurrencyRatesTicker, error) {
	return s.ticker, s.err
}

func TestUpdateCurrentTickers(t *testing.T) {
	prevTs := time.Now().Add(-time.Hour).UTC()
	newTs := time.Now().UTC()
	prev := func() *common.CurrencyRatesTicker {
		return &common.CurrencyRatesTicker{
			Timestamp:  prevTs,
			Rates:      map[string]float32{"usd": 1},
			TokenRates: map[string]float32{"0xa": 10, "0xb": 20},
		}
	}
	tests := []struct {
		name     string
		prev     *common.CurrencyRatesTicker
		ticker   *common.CurrencyRatesTicker
		err      error
		want     *common.CurrencyRatesTicker
		notified bool
	}{
		{
			name:     "complete ticker replaces previous one",
			prev:     prev(),
			ticker:   &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}, TokenRates: map[string]float32{"0xa": 11}},
			want:     &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}, TokenRates: map[string]float32{"0xa": 11}},
			notified: true,
		},
		{
			// a token from a failed batch must not carry its previous rate under the new timestamp
			name:     "incomplete tokens publish only the fetched token rates",
			prev:     prev(),
			ticker:   &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}, TokenRates: map[string]float32{"0xa": 11}},
			err:      fmt.Errorf("%w: 1 of 2 batches failed", errCoingeckoIncompleteTokenRates),
			want:     &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}, TokenRates: map[string]float32{"0xa": 11}},
			notified: true,
		},
		{
			name:     "incomplete tokens without previous ticker",
			ticker:   &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}},
			err:      fmt.Errorf("%w: coins/list failed", errCoingeckoIncompleteTokenRates),
			want:     &common.CurrencyRatesTicker{Timestamp: newTs, Rates: map[string]float32{"usd": 2}},
			notified: true,
		},
		{
			name: "native failure keeps previous ticker",
			prev: prev(),
			err:  errors.New("simple/price failed"),
			want: prev(),
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			config := common.Config{CoinName: "fakecoin"}
			d, _, tmp := setupRocksDB(t, &testBitcoinParser{BitcoinParser: bitcoinTestnetParser()}, &config)
			defer closeAndDestroyRocksDB(t, d, tmp)
			notified := false
			fr := &FiatRates{
				db:                  d,
				currentTicker:       tt.prev,
				downloader:          &stubCurrentTickersDownloader{ticker: tt.ticker, err: tt.err},
				callbackOnNewTicker: func(*common.CurrencyRatesTicker) { notified = true },
			}
			fr.updateCurrentTickers()
			if got := fr.GetCurrentTicker("", ""); !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("current ticker = %+v, want %+v", got, tt.want)
			}
			if notified != tt.notified {
				t.Fatalf("notified = %v, want %v", notified, tt.notified)
			}
			if !tt.notified {
				return
			}
			stored, err := d.FiatRatesGetSpecialTickers(currentTickersKey)
			if err != nil || stored == nil || len(*stored) != 1 {
				t.Fatalf("stored current ticker = %v, %v", stored, err)
			}
			if got := (*stored)[0].TokenRates; len(got)+len(tt.want.TokenRates) > 0 && !reflect.DeepEqual(got, tt.want.TokenRates) {
				t.Fatalf("stored TokenRates = %v, want %v", (*stored)[0].TokenRates, tt.want.TokenRates)
			}
		})
	}
}

func TestTokenPriceIdsBudget(t *testing.T) {
	for _, vs := range []string{"usd", "bnb", "eth", "matic-network"} {
		ids := strings.Repeat("a", tokenPriceIdsBudget(vs))
		query := url.Values{"ids": {ids}, "vs_currencies": {vs}}.Encode()
		if want := coingeckoMaxQueryLen - coingeckoQueryLenMargin; len(query) != want {
			t.Fatalf("vs=%s: query with a full ids budget is %d chars, want %d", vs, len(query), want)
		}
	}
}
