// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tx.proto

/*
Package bchain is a generated protocol buffer package.

It is generated from these files:
	tx.proto

It has these top-level messages:
	ProtoSyscoinTransaction
*/
package bchain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoSyscoinTransaction struct {
	Txid      []byte                              `protobuf:"bytes,1,opt,name=Txid,json=txid,proto3" json:"Txid,omitempty"`
	Hex       []byte                              `protobuf:"bytes,2,opt,name=Hex,json=hex,proto3" json:"Hex,omitempty"`
	Blocktime uint64                              `protobuf:"varint,3,opt,name=Blocktime,json=blocktime" json:"Blocktime,omitempty"`
	Locktime  uint32                              `protobuf:"varint,4,opt,name=Locktime,json=locktime" json:"Locktime,omitempty"`
	Height    uint32                              `protobuf:"varint,5,opt,name=Height,json=height" json:"Height,omitempty"`
	Vin       []*ProtoSyscoinTransaction_VinType  `protobuf:"bytes,6,rep,name=Vin,json=vin" json:"Vin,omitempty"`
	Vout      []*ProtoSyscoinTransaction_VoutType `protobuf:"bytes,7,rep,name=Vout,json=vout" json:"Vout,omitempty"`
	Version   int32                               `protobuf:"varint,8,opt,name=Version,json=version" json:"Version,omitempty"`
}

func (m *ProtoSyscoinTransaction) Reset()                    { *m = ProtoSyscoinTransaction{} }
func (m *ProtoSyscoinTransaction) String() string            { return proto.CompactTextString(m) }
func (*ProtoSyscoinTransaction) ProtoMessage()               {}
func (*ProtoSyscoinTransaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoSyscoinTransaction) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *ProtoSyscoinTransaction) GetHex() []byte {
	if m != nil {
		return m.Hex
	}
	return nil
}

func (m *ProtoSyscoinTransaction) GetBlocktime() uint64 {
	if m != nil {
		return m.Blocktime
	}
	return 0
}

func (m *ProtoSyscoinTransaction) GetLocktime() uint32 {
	if m != nil {
		return m.Locktime
	}
	return 0
}

func (m *ProtoSyscoinTransaction) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ProtoSyscoinTransaction) GetVin() []*ProtoSyscoinTransaction_VinType {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *ProtoSyscoinTransaction) GetVout() []*ProtoSyscoinTransaction_VoutType {
	if m != nil {
		return m.Vout
	}
	return nil
}

func (m *ProtoSyscoinTransaction) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type ProtoSyscoinTransaction_AssetInfoDetailsType struct {
	Symbol   string `protobuf:"bytes,1,opt,name=Symbol,json=symbol" json:"Symbol,omitempty"`
	Decimals int32  `protobuf:"varint,2,opt,name=Decimals,json=decimals" json:"Decimals,omitempty"`
}

func (m *ProtoSyscoinTransaction_AssetInfoDetailsType) Reset() {
	*m = ProtoSyscoinTransaction_AssetInfoDetailsType{}
}
func (m *ProtoSyscoinTransaction_AssetInfoDetailsType) String() string {
	return proto.CompactTextString(m)
}
func (*ProtoSyscoinTransaction_AssetInfoDetailsType) ProtoMessage() {}
func (*ProtoSyscoinTransaction_AssetInfoDetailsType) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

func (m *ProtoSyscoinTransaction_AssetInfoDetailsType) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ProtoSyscoinTransaction_AssetInfoDetailsType) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

type ProtoSyscoinTransaction_AssetInfoType struct {
	AssetGuid uint32                                        `protobuf:"varint,1,opt,name=AssetGuid,json=assetGuid" json:"AssetGuid,omitempty"`
	ValueSat  []byte                                        `protobuf:"bytes,2,opt,name=ValueSat,json=valueSat,proto3" json:"ValueSat,omitempty"`
	Details   *ProtoSyscoinTransaction_AssetInfoDetailsType `protobuf:"bytes,3,opt,name=Details,json=details" json:"Details,omitempty"`
}

func (m *ProtoSyscoinTransaction_AssetInfoType) Reset()         { *m = ProtoSyscoinTransaction_AssetInfoType{} }
func (m *ProtoSyscoinTransaction_AssetInfoType) String() string { return proto.CompactTextString(m) }
func (*ProtoSyscoinTransaction_AssetInfoType) ProtoMessage()    {}
func (*ProtoSyscoinTransaction_AssetInfoType) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1}
}

func (m *ProtoSyscoinTransaction_AssetInfoType) GetAssetGuid() uint32 {
	if m != nil {
		return m.AssetGuid
	}
	return 0
}

func (m *ProtoSyscoinTransaction_AssetInfoType) GetValueSat() []byte {
	if m != nil {
		return m.ValueSat
	}
	return nil
}

func (m *ProtoSyscoinTransaction_AssetInfoType) GetDetails() *ProtoSyscoinTransaction_AssetInfoDetailsType {
	if m != nil {
		return m.Details
	}
	return nil
}

type ProtoSyscoinTransaction_VinType struct {
	Coinbase     string                                 `protobuf:"bytes,1,opt,name=Coinbase,json=coinbase" json:"Coinbase,omitempty"`
	Txid         []byte                                 `protobuf:"bytes,2,opt,name=Txid,json=txid,proto3" json:"Txid,omitempty"`
	Vout         uint32                                 `protobuf:"varint,3,opt,name=Vout,json=vout" json:"Vout,omitempty"`
	ScriptSigHex []byte                                 `protobuf:"bytes,4,opt,name=ScriptSigHex,json=scriptSigHex,proto3" json:"ScriptSigHex,omitempty"`
	Sequence     uint32                                 `protobuf:"varint,5,opt,name=Sequence,json=sequence" json:"Sequence,omitempty"`
	Addresses    []string                               `protobuf:"bytes,6,rep,name=Addresses,json=addresses" json:"Addresses,omitempty"`
	AssetInfo    *ProtoSyscoinTransaction_AssetInfoType `protobuf:"bytes,7,opt,name=AssetInfo,json=assetInfo" json:"AssetInfo,omitempty"`
}

func (m *ProtoSyscoinTransaction_VinType) Reset()         { *m = ProtoSyscoinTransaction_VinType{} }
func (m *ProtoSyscoinTransaction_VinType) String() string { return proto.CompactTextString(m) }
func (*ProtoSyscoinTransaction_VinType) ProtoMessage()    {}
func (*ProtoSyscoinTransaction_VinType) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 2}
}

func (m *ProtoSyscoinTransaction_VinType) GetCoinbase() string {
	if m != nil {
		return m.Coinbase
	}
	return ""
}

func (m *ProtoSyscoinTransaction_VinType) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *ProtoSyscoinTransaction_VinType) GetVout() uint32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *ProtoSyscoinTransaction_VinType) GetScriptSigHex() []byte {
	if m != nil {
		return m.ScriptSigHex
	}
	return nil
}

func (m *ProtoSyscoinTransaction_VinType) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ProtoSyscoinTransaction_VinType) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *ProtoSyscoinTransaction_VinType) GetAssetInfo() *ProtoSyscoinTransaction_AssetInfoType {
	if m != nil {
		return m.AssetInfo
	}
	return nil
}

type ProtoSyscoinTransaction_VoutType struct {
	ValueSat        []byte                                 `protobuf:"bytes,1,opt,name=ValueSat,json=valueSat,proto3" json:"ValueSat,omitempty"`
	N               uint32                                 `protobuf:"varint,2,opt,name=N,json=n" json:"N,omitempty"`
	ScriptPubKeyHex []byte                                 `protobuf:"bytes,3,opt,name=ScriptPubKeyHex,json=scriptPubKeyHex,proto3" json:"ScriptPubKeyHex,omitempty"`
	Addresses       []string                               `protobuf:"bytes,4,rep,name=Addresses,json=addresses" json:"Addresses,omitempty"`
	AssetInfo       *ProtoSyscoinTransaction_AssetInfoType `protobuf:"bytes,5,opt,name=AssetInfo,json=assetInfo" json:"AssetInfo,omitempty"`
}

func (m *ProtoSyscoinTransaction_VoutType) Reset()         { *m = ProtoSyscoinTransaction_VoutType{} }
func (m *ProtoSyscoinTransaction_VoutType) String() string { return proto.CompactTextString(m) }
func (*ProtoSyscoinTransaction_VoutType) ProtoMessage()    {}
func (*ProtoSyscoinTransaction_VoutType) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 3}
}

func (m *ProtoSyscoinTransaction_VoutType) GetValueSat() []byte {
	if m != nil {
		return m.ValueSat
	}
	return nil
}

func (m *ProtoSyscoinTransaction_VoutType) GetN() uint32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *ProtoSyscoinTransaction_VoutType) GetScriptPubKeyHex() []byte {
	if m != nil {
		return m.ScriptPubKeyHex
	}
	return nil
}

func (m *ProtoSyscoinTransaction_VoutType) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *ProtoSyscoinTransaction_VoutType) GetAssetInfo() *ProtoSyscoinTransaction_AssetInfoType {
	if m != nil {
		return m.AssetInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoSyscoinTransaction)(nil), "bchain.ProtoSyscoinTransaction")
	proto.RegisterType((*ProtoSyscoinTransaction_AssetInfoDetailsType)(nil), "bchain.ProtoSyscoinTransaction.AssetInfoDetailsType")
	proto.RegisterType((*ProtoSyscoinTransaction_AssetInfoType)(nil), "bchain.ProtoSyscoinTransaction.AssetInfoType")
	proto.RegisterType((*ProtoSyscoinTransaction_VinType)(nil), "bchain.ProtoSyscoinTransaction.VinType")
	proto.RegisterType((*ProtoSyscoinTransaction_VoutType)(nil), "bchain.ProtoSyscoinTransaction.VoutType")
}

func init() { proto.RegisterFile("tx.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0xe5, 0x25, 0xcd, 0x1f, 0xaf, 0xd5, 0x90, 0x85, 0x20, 0xaa, 0x76, 0x88, 0x76, 0x21,
	0x17, 0x7a, 0x18, 0x5c, 0x90, 0xb8, 0x00, 0x93, 0x18, 0x0c, 0x4d, 0x93, 0x53, 0xe5, 0xee, 0x24,
	0x66, 0xb5, 0x48, 0xed, 0x12, 0x3b, 0x55, 0xfa, 0x51, 0xf8, 0x48, 0x9c, 0xf9, 0x32, 0x1c, 0x91,
	0xdf, 0x38, 0xd5, 0x8a, 0x80, 0x21, 0xed, 0xf8, 0x3c, 0xee, 0xeb, 0xf8, 0xf7, 0xd3, 0x5b, 0x1c,
	0x99, 0x7e, 0xb1, 0x69, 0x95, 0x51, 0x24, 0x28, 0xab, 0x15, 0x13, 0xf2, 0xec, 0x47, 0x88, 0x9f,
	0xde, 0xd8, 0x26, 0xdf, 0xe9, 0x4a, 0x09, 0xb9, 0x6c, 0x99, 0xd4, 0xac, 0x32, 0x42, 0x49, 0x42,
	0xb0, 0xbf, 0xec, 0x45, 0x9d, 0xa0, 0x14, 0x65, 0x53, 0xea, 0x9b, 0x5e, 0xd4, 0xe4, 0x11, 0xf6,
	0x2e, 0x79, 0x9f, 0x1c, 0x41, 0xe5, 0xad, 0x78, 0x4f, 0x4e, 0x71, 0xfc, 0xb6, 0x51, 0xd5, 0x17,
	0x23, 0xd6, 0x3c, 0xf1, 0x52, 0x94, 0xf9, 0x34, 0x2e, 0xc7, 0x82, 0xcc, 0x71, 0xf4, 0x69, 0x3c,
	0xf4, 0x53, 0x94, 0xcd, 0x68, 0xb4, 0x3f, 0x7b, 0x82, 0x83, 0x4b, 0x2e, 0x6e, 0x57, 0x26, 0x99,
	0xc0, 0x49, 0xb0, 0x82, 0x44, 0x5e, 0x61, 0xaf, 0x10, 0x32, 0x09, 0x52, 0x2f, 0x3b, 0x3e, 0x7f,
	0xb6, 0x18, 0x5e, 0xba, 0xf8, 0xcb, 0x2b, 0x17, 0x85, 0x90, 0xcb, 0xdd, 0x86, 0x53, 0x6f, 0x2b,
	0x24, 0x79, 0x8d, 0xfd, 0x42, 0x75, 0x26, 0x09, 0x61, 0x36, 0xbb, 0x77, 0x56, 0x75, 0x06, 0x86,
	0xfd, 0xad, 0xea, 0x0c, 0x49, 0x70, 0x58, 0xf0, 0x56, 0x0b, 0x25, 0x93, 0x28, 0x45, 0xd9, 0x84,
	0x86, 0xdb, 0x21, 0xce, 0x3f, 0xe2, 0xc7, 0x6f, 0xb4, 0xe6, 0xe6, 0x83, 0xfc, 0xac, 0x2e, 0xb8,
	0x61, 0xa2, 0xd1, 0x76, 0xce, 0x22, 0xe4, 0xbb, 0x75, 0xa9, 0x1a, 0x90, 0x14, 0xd3, 0x40, 0x43,
	0xb2, 0xd8, 0x17, 0xbc, 0x12, 0x6b, 0xd6, 0x68, 0x70, 0x35, 0xa1, 0x51, 0xed, 0xf2, 0xfc, 0x1b,
	0xc2, 0xb3, 0xfd, 0x65, 0x70, 0xcb, 0x29, 0x8e, 0xa1, 0x78, 0xdf, 0x39, 0xdb, 0x33, 0x1a, 0xb3,
	0xb1, 0xb0, 0x77, 0x15, 0xac, 0xe9, 0x78, 0xce, 0x8c, 0xf3, 0x1e, 0x6d, 0x5d, 0x26, 0xd7, 0x38,
	0x74, 0xcf, 0x01, 0xf5, 0xc7, 0xe7, 0x2f, 0xef, 0x43, 0xfe, 0x13, 0x06, 0x0d, 0xeb, 0x21, 0xcc,
	0x7f, 0x22, 0x1c, 0x3a, 0xa1, 0xf6, 0xbb, 0xef, 0x94, 0x90, 0x25, 0xd3, 0xdc, 0xd1, 0x45, 0x95,
	0xcb, 0xfb, 0xd5, 0x38, 0xba, 0xb3, 0x1a, 0xc4, 0xb9, 0xf7, 0x00, 0x60, 0x30, 0x7a, 0x86, 0xa7,
	0x79, 0xd5, 0x8a, 0x8d, 0xc9, 0xc5, 0xad, 0xdd, 0x1b, 0x1f, 0x7e, 0x3f, 0xd5, 0x77, 0x3a, 0xfb,
	0x9d, 0x9c, 0x7f, 0xed, 0xb8, 0xac, 0xb8, 0x5b, 0x84, 0x48, 0xbb, 0x0c, 0x66, 0xea, 0xba, 0xe5,
	0x5a, 0x73, 0x0d, 0x0b, 0x11, 0xd3, 0x98, 0x8d, 0x05, 0xb9, 0x72, 0xde, 0x2c, 0x4e, 0x12, 0x02,
	0xff, 0xf3, 0xff, 0xe6, 0x07, 0xf0, 0x41, 0xb3, 0x8d, 0xf3, 0xef, 0x08, 0x47, 0xe3, 0x3e, 0x1c,
	0x38, 0x47, 0xbf, 0x39, 0x9f, 0x62, 0x74, 0x0d, 0xe0, 0x33, 0x8a, 0x24, 0xc9, 0xf0, 0xc9, 0x40,
	0x78, 0xd3, 0x95, 0x57, 0x7c, 0x67, 0x21, 0x3d, 0x18, 0x38, 0xd1, 0x87, 0xf5, 0x21, 0x8b, 0xff,
	0x4f, 0x96, 0xc9, 0xc3, 0x58, 0xca, 0x00, 0xfe, 0xe4, 0x2f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xf5, 0xba, 0x41, 0xac, 0xf0, 0x03, 0x00, 0x00,
}