DENARIUS_VERSION := 2.5.2.0

all:
	wget https://github.com/carsenk/denarius/releases/download/v2.5.2/denariusd-2.5.2.0_ubuntu16.tar.gz
	tar -xvf denariusd-2.5.2.0_ubuntu16.tar.gz
	mv denariusd-2.5.2.0_ubuntu16 denarius


clean:
	rm -rf denarius
	rm -f denariusd-2.5.2.0_ubuntu16.tar.gz
